AWSTemplateFormatVersion: "2010-09-09"
Description: Launch an EC2 instance for data processing

Parameters:
    InstanceImageId:
        Type: AWS::EC2::Image::Id
        Description: Instance image Id
        Default: 'ami-0947d2ba12ee1ff75'
    InstanceType:
        Type: String
        Description: Allowed instance types
        Default: 't2.micro'
        AllowedValues:
            - 't2.micro'
    InstanceKeyPair:
        Type: AWS::EC2::KeyPair::KeyName
        Description: SSH KeyPair for the instance
    InstanceSubnetId:
        Type: AWS::EC2::Subnet::Id
        Description: Subnet for the instance
    InstanceName:
        Type: String
        Description: The instance name configured as a tag
    InstanceUserData:
        Type: String
        Description: Script contents to execute on boot
        Default: ''
    VPC:
        Type: String
        Description: Deployment VPC

# TODO roles and policies should not be defined here
# TODO fine-tune policies

Resources:

    SshSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Simple SSH security group
            SecurityGroupIngress:
                CidrIp: 0.0.0.0/0
                IpProtocol: tcp
                ToPort: 22
                FromPort: 22
            VpcId: !Ref VPC

    S3AccessRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Principal:
                        Service: 
                          - ec2.amazonaws.com
                    Action:
                      - 'sts:AssumeRole'
            Path: /
            Policies:
              - PolicyName: S3AccessPolicy
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - s3:ListBucketMultipartUploads
                          - s3:ListBucketVersions
                          - s3:ListBucket
                          - s3:ListMultipartUploadParts
                        Resource:
                          - arn:aws:s3:::floresj4-cfn-ec2-processing
                          - arn:aws:s3:::*/*

    BatchProcessingInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
                - !Ref S3AccessRole

    BatchProcessingInstance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref InstanceImageId
            InstanceType: !Ref InstanceType
            KeyName: !Ref InstanceKeyPair
            SubnetId: !Ref InstanceSubnetId
            SecurityGroupIds:
                - !Ref SshSecurityGroup
            IamInstanceProfile: !Ref BatchProcessingInstanceProfile
            UserData: !Ref InstanceUserData
            Tags:
                - Key: Name
                  Value: !Ref InstanceName